
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void my_kernel_kernel1(float* __restrict__ T_multiply, float* __restrict__ DepthwiseConv2d, float* __restrict__ placeholder) {
  T_multiply[(((((int)blockIdx.x) * 32) + ((int)threadIdx.x)))] = ((DepthwiseConv2d[(((((int)blockIdx.x) * 32) + ((int)threadIdx.x)))] + placeholder[((((((int)blockIdx.x) * 32) + ((int)threadIdx.x)) % 672))]) * (max(min(((DepthwiseConv2d[(((((int)blockIdx.x) * 32) + ((int)threadIdx.x)))] + placeholder[((((((int)blockIdx.x) * 32) + ((int)threadIdx.x)) % 672))]) + 3.000000e+00f), 6.000000e+00f), 0.000000e+00f) * 1.666667e-01f));
}

extern "C" __global__ void my_kernel_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ DepthwiseConv2d) {
  float DepthwiseConv2d_local[192];
  __shared__ float PaddedInput_shared[89376];
  __shared__ float placeholder_shared[4200];
  for (int i_c_outer_inner_init = 0; i_c_outer_inner_init < 2; ++i_c_outer_inner_init) {
    for (int j_c_outer_inner_init = 0; j_c_outer_inner_init < 2; ++j_c_outer_inner_init) {
      DepthwiseConv2d_local[(((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 48))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 96))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 144))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 6))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 54))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 102))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 150))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 1))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 49))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 97))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 145))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 7))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 55))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 103))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 151))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 2))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 50))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 98))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 146))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 8))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 56))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 104))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 152))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 3))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 51))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 99))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 147))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 9))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 57))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 105))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 153))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 4))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 52))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 100))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 148))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 10))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 58))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 106))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 154))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 5))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 53))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 101))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 149))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 11))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 59))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 107))] = 0.000000e+00f;
      DepthwiseConv2d_local[((((i_c_outer_inner_init * 24) + (j_c_outer_inner_init * 12)) + 155))] = 0.000000e+00f;
    }
  }
  for (int ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer = 0; ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer < 1596; ++ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer) {
    PaddedInput_shared[(((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)))] = (((((2 <= (((((int)blockIdx.x) >> 2) * 4) + ((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 22344) / 3192))) && ((((((int)blockIdx.x) >> 2) * 4) + ((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 22344) / 3192)) < 18)) && (336 <= (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 3192))) && ((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 3192) < 3024)) ? placeholder[(((((((((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) / 22344) * 172032) + ((((int)blockIdx.x) >> 2) * 43008)) + (((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 22344) / 3192) * 10752)) + (((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 3192) / 168) * 672)) + ((((int)blockIdx.x) & 3) * 168)) + (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 56) + ((int)threadIdx.x)) % 168)) - 22848))] : 0.000000e+00f);
  }
  for (int ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer1 = 0; ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer1 < 75; ++ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer1) {
    placeholder_shared[(((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer1 * 56) + ((int)threadIdx.x)))] = placeholder1[(((((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer1 * 56) + ((int)threadIdx.x)) / 168) * 672) + ((((int)blockIdx.x) & 3) * 168)) + (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer1 * 56) + ((int)threadIdx.x)) % 168)))];
  }
  __syncthreads();
  for (int di_outer_inner = 0; di_outer_inner < 5; ++di_outer_inner) {
    for (int i_c_outer_inner = 0; i_c_outer_inner < 2; ++i_c_outer_inner) {
      for (int j_c_outer_inner = 0; j_c_outer_inner < 2; ++j_c_outer_inner) {
        for (int c_c_outer_inner = 0; c_c_outer_inner < 6; ++c_c_outer_inner) {
          DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] = (DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] + (PaddedInput_shared[(((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 22344))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 44688))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67032))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 22680))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45024))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67368))] * placeholder_shared[((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner))]));
          DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] = (DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 22512))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 44856))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67200))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 22848))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45192))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67536))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 168))]));
          DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] = (DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 22680))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45024))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67368))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 23016))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45360))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67704))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 336))]));
          DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] = (DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 22848))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45192))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67536))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 840))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 23184))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45528))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67872))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 504))]));
          DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] = (DepthwiseConv2d_local[((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 48))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 23016))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 96))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45360))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 144))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 67704))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 6))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 1008))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 54))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 23352))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 102))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 45696))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
          DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] = (DepthwiseConv2d_local[(((((i_c_outer_inner * 24) + (j_c_outer_inner * 12)) + c_c_outer_inner) + 150))] + (PaddedInput_shared[((((((((i_c_outer_inner * 6384) + (di_outer_inner * 3192)) + ((((int)threadIdx.x) / 28) * 1344)) + (j_c_outer_inner * 672)) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 68040))] * placeholder_shared[(((((di_outer_inner * 840) + ((((int)threadIdx.x) % 28) * 6)) + c_c_outer_inner) + 672))]));
        }
      }
    }
  }
  for (int i_inner = 0; i_inner < 2; ++i_inner) {
    for (int j_inner = 0; j_inner < 4; ++j_inner) {
      for (int c_inner = 0; c_inner < 6; ++c_inner) {
        DepthwiseConv2d[(((((((((((int)blockIdx.x) >> 2) * 10752) + (i_inner * 5376)) + ((((int)threadIdx.x) / 28) * 2688)) + (j_inner * 672)) + ((((int)blockIdx.x) & 3) * 168)) + ((((int)threadIdx.x) % 28) * 6)) + c_inner))] = DepthwiseConv2d_local[((((i_inner * 24) + (j_inner * 6)) + c_inner))];
        DepthwiseConv2d[((((((((((((int)blockIdx.x) >> 2) * 10752) + (i_inner * 5376)) + ((((int)threadIdx.x) / 28) * 2688)) + (j_inner * 672)) + ((((int)blockIdx.x) & 3) * 168)) + ((((int)threadIdx.x) % 28) * 6)) + c_inner) + 43008))] = DepthwiseConv2d_local[(((((i_inner * 24) + (j_inner * 6)) + c_inner) + 48))];
        DepthwiseConv2d[((((((((((((int)blockIdx.x) >> 2) * 10752) + (i_inner * 5376)) + ((((int)threadIdx.x) / 28) * 2688)) + (j_inner * 672)) + ((((int)blockIdx.x) & 3) * 168)) + ((((int)threadIdx.x) % 28) * 6)) + c_inner) + 86016))] = DepthwiseConv2d_local[(((((i_inner * 24) + (j_inner * 6)) + c_inner) + 96))];
        DepthwiseConv2d[((((((((((((int)blockIdx.x) >> 2) * 10752) + (i_inner * 5376)) + ((((int)threadIdx.x) / 28) * 2688)) + (j_inner * 672)) + ((((int)blockIdx.x) & 3) * 168)) + ((((int)threadIdx.x) % 28) * 6)) + c_inner) + 129024))] = DepthwiseConv2d_local[(((((i_inner * 24) + (j_inner * 6)) + c_inner) + 144))];
      }
    }
  }
}


