
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void my_kernel_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ T_relu, float* __restrict__ placeholder2, float* __restrict__ placeholder3) {
  float conv2d_transpose_nhwc[1536];
  __shared__ float PadInput_shared[2912];
  __shared__ float placeholder_shared[512];
  for (int n_outer_inner_init = 0; n_outer_inner_init < 2; ++n_outer_inner_init) {
    for (int w_outer_inner_init = 0; w_outer_inner_init < 3; ++w_outer_inner_init) {
      for (int co_outer_inner_init = 0; co_outer_inner_init < 4; ++co_outer_inner_init) {
        conv2d_transpose_nhwc[((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 192))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 384))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 576))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 768))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 960))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1152))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1344))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 12))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 204))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 396))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 588))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 780))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 972))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1164))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1356))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 24))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 216))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 408))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 600))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 792))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 984))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1176))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1368))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 36))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 228))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 420))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 612))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 804))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 996))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1188))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1380))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 48))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 240))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 432))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 624))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 816))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1008))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1200))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1392))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 60))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 252))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 444))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 636))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 828))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1020))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1212))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1404))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 72))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 264))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 456))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 648))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 840))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1032))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1224))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1416))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 84))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 276))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 468))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 660))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 852))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1044))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1236))] = 0.000000e+00f;
        conv2d_transpose_nhwc[(((((n_outer_inner_init * 96) + (w_outer_inner_init * 4)) + co_outer_inner_init) + 1428))] = 0.000000e+00f;
      }
    }
  }
  for (int rw_outer_outer = 0; rw_outer_outer < 2; ++rw_outer_outer) {
    for (int rc_outer_outer = 0; rc_outer_outer < 128; ++rc_outer_outer) {
      __syncthreads();
      for (int ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer = 0; ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer < 122; ++ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer) {
        if (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) < 728) {
          if (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 24) + ((int)threadIdx.x)) < 2912) {
            PadInput_shared[(((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 24) + ((int)threadIdx.x)))] = (((((13 <= (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) % 182)) && ((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) % 182) < 169)) && (1 <= (rw_outer_outer + (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) % 13)))) && ((rw_outer_outer + (((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) % 13)) < 13)) ? placeholder[(((((((((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) / 182) * 73728) + (((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) % 182) / 13) * 6144)) + (rw_outer_outer * 512)) + ((((ax0_ax1_fused_ax2_fused_ax3_fused_outer_outer * 6) + (((int)threadIdx.x) >> 2)) % 13) * 512)) + (rc_outer_outer * 4)) + (((int)threadIdx.x) & 3)) - 6656))] : 0.000000e+00f);
          }
        }
      }
      placeholder_shared[(((int)threadIdx.x))] = placeholder1[(((((((rc_outer_outer * 1024) + ((((int)threadIdx.x) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 24))] = placeholder1[(((((((rc_outer_outer * 1024) + (((((int)threadIdx.x) + 24) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 48))] = placeholder1[((((((((((((int)threadIdx.x) + 48) >> 6) * 131072) + (rc_outer_outer * 1024)) + ((((((int)threadIdx.x) + 48) & 63) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 72))] = placeholder1[((((((((((((int)threadIdx.x) + 72) >> 6) * 131072) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 8) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 96))] = placeholder1[((((((((((((int)threadIdx.x) + 96) >> 6) * 131072) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 32) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 120))] = placeholder1[(((((((((((((int)threadIdx.x) + 120) >> 7) * 524288) + ((((((int)threadIdx.x) + 120) & 127) >> 6) * 131072)) + (rc_outer_outer * 1024)) + ((((((int)threadIdx.x) + 56) & 63) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 144))] = placeholder1[((((((((((((int)threadIdx.x) + 144) >> 7) * 524288) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 16) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 168))] = placeholder1[((((((((((((int)threadIdx.x) + 168) >> 7) * 524288) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 40) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 192))] = placeholder1[(((((((((((((int)threadIdx.x) + 192) >> 7) * 524288) + (((((int)threadIdx.x) + 64) >> 6) * 131072)) + (rc_outer_outer * 1024)) + ((((int)threadIdx.x) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 216))] = placeholder1[(((((((((((((int)threadIdx.x) + 216) >> 7) * 524288) + (((((int)threadIdx.x) + 88) >> 6) * 131072)) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 24) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 240))] = placeholder1[(((((((((((((int)threadIdx.x) + 240) >> 7) * 524288) + ((((((int)threadIdx.x) + 112) & 127) >> 6) * 131072)) + (rc_outer_outer * 1024)) + ((((((int)threadIdx.x) + 48) & 63) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 264))] = placeholder1[((((((((((((int)threadIdx.x) + 264) >> 7) * 524288) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 8) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 288))] = placeholder1[((((((((((((int)threadIdx.x) + 288) >> 7) * 524288) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 32) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 312))] = placeholder1[(((((((((((((int)threadIdx.x) + 312) >> 7) * 524288) + (((((int)threadIdx.x) + 56) >> 6) * 131072)) + (rc_outer_outer * 1024)) + ((((((int)threadIdx.x) + 56) & 63) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 336))] = placeholder1[(((((((((((((int)threadIdx.x) + 336) >> 7) * 524288) + (((((int)threadIdx.x) + 80) >> 6) * 131072)) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 16) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 360))] = placeholder1[(((((((((((((int)threadIdx.x) + 360) >> 7) * 524288) + (((((int)threadIdx.x) + 104) >> 6) * 131072)) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 40) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 384))] = placeholder1[(((((((rc_outer_outer * 1024) + ((((int)threadIdx.x) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 1835008) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 408))] = placeholder1[((((((((((((int)threadIdx.x) + 408) >> 7) * 524288) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 24) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 432))] = placeholder1[(((((((((((((int)threadIdx.x) + 432) >> 7) * 524288) + (((((int)threadIdx.x) + 48) >> 6) * 131072)) + (rc_outer_outer * 1024)) + ((((((int)threadIdx.x) + 48) & 63) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 456))] = placeholder1[(((((((((((((int)threadIdx.x) + 456) >> 7) * 524288) + (((((int)threadIdx.x) + 72) >> 6) * 131072)) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 8) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) + 8) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      placeholder_shared[((((int)threadIdx.x) + 480))] = placeholder1[(((((((((((((int)threadIdx.x) + 480) >> 7) * 524288) + (((((int)threadIdx.x) + 96) >> 6) * 131072)) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 32) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) & 15)) + 262144) - (rw_outer_outer * 262144)))];
      if (((int)threadIdx.x) < 8) {
        placeholder_shared[((((int)threadIdx.x) + 504))] = placeholder1[(((((((((((((int)threadIdx.x) + 504) >> 7) * 524288) + (((((int)threadIdx.x) + 120) >> 6) * 131072)) + (rc_outer_outer * 1024)) + (((((int)threadIdx.x) + 56) >> 4) * 256)) + (((int)blockIdx.x) * 16)) + (((int)threadIdx.x) + 8)) + 262144) - (rw_outer_outer * 262144)))];
      }
      __syncthreads();
      for (int rh_outer_inner = 0; rh_outer_inner < 2; ++rh_outer_inner) {
        for (int rw_outer_inner = 0; rw_outer_inner < 2; ++rw_outer_inner) {
          for (int n_outer_inner = 0; n_outer_inner < 2; ++n_outer_inner) {
            for (int w_outer_inner = 0; w_outer_inner < 3; ++w_outer_inner) {
              for (int co_outer_inner = 0; co_outer_inner < 4; ++co_outer_inner) {
                for (int rh_inner = 0; rh_inner < 2; ++rh_inner) {
                  for (int rc_inner = 0; rc_inner < 4; ++rc_inner) {
                    conv2d_transpose_nhwc[((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner))] = (conv2d_transpose_nhwc[((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 192))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 192))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 384))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 384))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 12))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 576))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 576))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 768))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 768))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 24))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 960))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 960))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1152))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1152))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 36))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1344))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1344))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 12))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 12))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 204))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 204))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 396))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 396))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 12))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 588))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 588))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 780))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 780))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 24))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 972))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 972))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1164))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1164))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 36))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1356))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1356))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 1) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 24))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 24))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 52))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 216))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 216))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner) + 52))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 408))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 408))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 64))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 600))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 600))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner) + 52))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 792))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 792))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 76))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 984))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 984))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner) + 52))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1176))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1176))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 88))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1368))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1368))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner) + 52))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 36))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 36))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 228))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 228))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 420))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 420))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 12))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 612))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 612))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 804))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 804))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 24))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 996))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 996))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1188))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1188))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 36))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1380))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1380))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 3) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 48))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 48))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 104))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 240))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 240))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner) + 104))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 432))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 432))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 116))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 624))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 624))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner) + 104))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 816))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 816))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 128))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1008))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1008))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner) + 104))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1200))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1200))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 140))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1392))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1392))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner) + 104))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 60))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 60))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 252))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 252))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 444))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 444))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 12))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 636))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 636))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 828))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 828))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 24))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1020))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1020))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1212))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1212))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 36))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1404))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1404))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 5) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 72))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 72))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 156))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 264))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 264))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner) + 156))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 456))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 456))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 168))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 648))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 648))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner) + 156))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 840))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 840))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 180))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1032))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1032))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner) + 156))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1224))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1224))] + ((((rh_inner == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 192))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1416))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1416))] + ((((rh_inner == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner) + 156))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 84))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 84))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 276))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 276))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 3) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 468))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 468))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 12))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 660))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 660))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 9) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 852))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 852))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 24))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1044))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1044))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 15) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1236))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1236))] + ((((((rh_inner + 1) % 2) == 0) && (((w_outer_inner + rw_outer_inner) % 2) == 0)) ? PadInput_shared[((((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + (((w_outer_inner + rw_outer_inner) >> 1) * 4)) + rc_inner) + 36))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                    conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1428))] = (conv2d_transpose_nhwc[(((((n_outer_inner * 96) + (w_outer_inner * 4)) + co_outer_inner) + 1428))] + ((((((rh_inner + 1) % 2) == 0) && ((((w_outer_inner + rw_outer_inner) + 1) % 2) == 0)) ? PadInput_shared[(((((((((((int)threadIdx.x) / 12) * 1456) + (n_outer_inner * 728)) + (((((int)threadIdx.x) % 12) >> 2) * 208)) + (((rh_inner + 7) >> 1) * 52)) + (rh_outer_inner * 52)) + ((((w_outer_inner + rw_outer_inner) + 21) >> 1) * 4)) + rc_inner))] : 0.000000e+00f) * placeholder_shared[((((((((rc_inner * 16) + ((((int)threadIdx.x) & 3) * 4)) + co_outer_inner) + 448) - (rw_outer_inner * 64)) - (rh_inner * 128)) - (rh_outer_inner * 256)))]));
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  for (int ax0_inner = 0; ax0_inner < 2; ++ax0_inner) {
    for (int ax1_inner = 0; ax1_inner < 8; ++ax1_inner) {
      for (int ax2_inner = 0; ax2_inner < 3; ++ax2_inner) {
        for (int ax3_inner = 0; ax3_inner < 4; ++ax3_inner) {
          T_relu[((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))] = max(((conv2d_transpose_nhwc[(((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 768))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 192))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 1536))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 384))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 2304))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 576))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 3072))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 768))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 3840))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 960))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 4608))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 1152))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
          T_relu[(((((((((((((int)threadIdx.x) / 12) * 294912) + (ax0_inner * 147456)) + (((((int)threadIdx.x) % 12) >> 2) * 49152)) + (ax1_inner * 6144)) + (ax2_inner * 256)) + (((int)blockIdx.x) * 16)) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner) + 5376))] = max(((conv2d_transpose_nhwc[((((((ax0_inner * 96) + (ax1_inner * 12)) + (ax2_inner * 4)) + ax3_inner) + 1344))] * placeholder2[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]) + placeholder3[((((((int)blockIdx.x) * 16) + ((((int)threadIdx.x) & 3) * 4)) + ax3_inner))]), 0.000000e+00f);
        }
      }
    }
  }
}


