
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void my_kernel_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ T_add, float* __restrict__ placeholder2) {
  float T_dense[20];
  __shared__ float placeholder_d_shared[4];
  __shared__ float placeholder_shared[4000];
  T_dense[(0)] = 0.000000e+00f;
  T_dense[(4)] = 0.000000e+00f;
  T_dense[(8)] = 0.000000e+00f;
  T_dense[(12)] = 0.000000e+00f;
  T_dense[(16)] = 0.000000e+00f;
  T_dense[(1)] = 0.000000e+00f;
  T_dense[(5)] = 0.000000e+00f;
  T_dense[(9)] = 0.000000e+00f;
  T_dense[(13)] = 0.000000e+00f;
  T_dense[(17)] = 0.000000e+00f;
  T_dense[(2)] = 0.000000e+00f;
  T_dense[(6)] = 0.000000e+00f;
  T_dense[(10)] = 0.000000e+00f;
  T_dense[(14)] = 0.000000e+00f;
  T_dense[(18)] = 0.000000e+00f;
  T_dense[(3)] = 0.000000e+00f;
  T_dense[(7)] = 0.000000e+00f;
  T_dense[(11)] = 0.000000e+00f;
  T_dense[(15)] = 0.000000e+00f;
  T_dense[(19)] = 0.000000e+00f;
  for (int k_outer_outer = 0; k_outer_outer < 128; ++k_outer_outer) {
    __syncthreads();
    if (((int)threadIdx.x) < 4) {
      placeholder_d_shared[(((int)threadIdx.x))] = placeholder[(((k_outer_outer * 4) + ((int)threadIdx.x)))];
    }
    placeholder_shared[(((int)threadIdx.x))] = placeholder1[(((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 50))] = placeholder1[((((((((int)threadIdx.x) + 50) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 100))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 12800))];
    placeholder_shared[((((int)threadIdx.x) + 150))] = placeholder1[((((((((int)threadIdx.x) + 150) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 200))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 25600))];
    placeholder_shared[((((int)threadIdx.x) + 250))] = placeholder1[((((((((int)threadIdx.x) + 250) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 300))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 38400))];
    placeholder_shared[((((int)threadIdx.x) + 350))] = placeholder1[((((((((int)threadIdx.x) + 350) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 400))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 51200))];
    placeholder_shared[((((int)threadIdx.x) + 450))] = placeholder1[((((((((int)threadIdx.x) + 450) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 500))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 64000))];
    placeholder_shared[((((int)threadIdx.x) + 550))] = placeholder1[((((((((int)threadIdx.x) + 550) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 600))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 76800))];
    placeholder_shared[((((int)threadIdx.x) + 650))] = placeholder1[((((((((int)threadIdx.x) + 650) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 700))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 89600))];
    placeholder_shared[((((int)threadIdx.x) + 750))] = placeholder1[((((((((int)threadIdx.x) + 750) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 800))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 102400))];
    placeholder_shared[((((int)threadIdx.x) + 850))] = placeholder1[((((((((int)threadIdx.x) + 850) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 900))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 115200))];
    placeholder_shared[((((int)threadIdx.x) + 950))] = placeholder1[((((((((int)threadIdx.x) + 950) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1000))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 128000))];
    placeholder_shared[((((int)threadIdx.x) + 1050))] = placeholder1[((((((((int)threadIdx.x) + 1050) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1100))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 140800))];
    placeholder_shared[((((int)threadIdx.x) + 1150))] = placeholder1[((((((((int)threadIdx.x) + 1150) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1200))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 153600))];
    placeholder_shared[((((int)threadIdx.x) + 1250))] = placeholder1[((((((((int)threadIdx.x) + 1250) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1300))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 166400))];
    placeholder_shared[((((int)threadIdx.x) + 1350))] = placeholder1[((((((((int)threadIdx.x) + 1350) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1400))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 179200))];
    placeholder_shared[((((int)threadIdx.x) + 1450))] = placeholder1[((((((((int)threadIdx.x) + 1450) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1500))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 192000))];
    placeholder_shared[((((int)threadIdx.x) + 1550))] = placeholder1[((((((((int)threadIdx.x) + 1550) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1600))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 204800))];
    placeholder_shared[((((int)threadIdx.x) + 1650))] = placeholder1[((((((((int)threadIdx.x) + 1650) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1700))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 217600))];
    placeholder_shared[((((int)threadIdx.x) + 1750))] = placeholder1[((((((((int)threadIdx.x) + 1750) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1800))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 230400))];
    placeholder_shared[((((int)threadIdx.x) + 1850))] = placeholder1[((((((((int)threadIdx.x) + 1850) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 1900))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 243200))];
    placeholder_shared[((((int)threadIdx.x) + 1950))] = placeholder1[((((((((int)threadIdx.x) + 1950) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2000))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 256000))];
    placeholder_shared[((((int)threadIdx.x) + 2050))] = placeholder1[((((((((int)threadIdx.x) + 2050) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2100))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 268800))];
    placeholder_shared[((((int)threadIdx.x) + 2150))] = placeholder1[((((((((int)threadIdx.x) + 2150) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2200))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 281600))];
    placeholder_shared[((((int)threadIdx.x) + 2250))] = placeholder1[((((((((int)threadIdx.x) + 2250) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2300))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 294400))];
    placeholder_shared[((((int)threadIdx.x) + 2350))] = placeholder1[((((((((int)threadIdx.x) + 2350) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2400))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 307200))];
    placeholder_shared[((((int)threadIdx.x) + 2450))] = placeholder1[((((((((int)threadIdx.x) + 2450) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2500))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 320000))];
    placeholder_shared[((((int)threadIdx.x) + 2550))] = placeholder1[((((((((int)threadIdx.x) + 2550) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2600))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 332800))];
    placeholder_shared[((((int)threadIdx.x) + 2650))] = placeholder1[((((((((int)threadIdx.x) + 2650) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2700))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 345600))];
    placeholder_shared[((((int)threadIdx.x) + 2750))] = placeholder1[((((((((int)threadIdx.x) + 2750) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2800))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 358400))];
    placeholder_shared[((((int)threadIdx.x) + 2850))] = placeholder1[((((((((int)threadIdx.x) + 2850) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 2900))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 371200))];
    placeholder_shared[((((int)threadIdx.x) + 2950))] = placeholder1[((((((((int)threadIdx.x) + 2950) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3000))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 384000))];
    placeholder_shared[((((int)threadIdx.x) + 3050))] = placeholder1[((((((((int)threadIdx.x) + 3050) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3100))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 396800))];
    placeholder_shared[((((int)threadIdx.x) + 3150))] = placeholder1[((((((((int)threadIdx.x) + 3150) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3200))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 409600))];
    placeholder_shared[((((int)threadIdx.x) + 3250))] = placeholder1[((((((((int)threadIdx.x) + 3250) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3300))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 422400))];
    placeholder_shared[((((int)threadIdx.x) + 3350))] = placeholder1[((((((((int)threadIdx.x) + 3350) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3400))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 435200))];
    placeholder_shared[((((int)threadIdx.x) + 3450))] = placeholder1[((((((((int)threadIdx.x) + 3450) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3500))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 448000))];
    placeholder_shared[((((int)threadIdx.x) + 3550))] = placeholder1[((((((((int)threadIdx.x) + 3550) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3600))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 460800))];
    placeholder_shared[((((int)threadIdx.x) + 3650))] = placeholder1[((((((((int)threadIdx.x) + 3650) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3700))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 473600))];
    placeholder_shared[((((int)threadIdx.x) + 3750))] = placeholder1[((((((((int)threadIdx.x) + 3750) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3800))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 486400))];
    placeholder_shared[((((int)threadIdx.x) + 3850))] = placeholder1[((((((((int)threadIdx.x) + 3850) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    placeholder_shared[((((int)threadIdx.x) + 3900))] = placeholder1[((((((((int)threadIdx.x) >> 2) * 512) + (k_outer_outer * 4)) + (((int)threadIdx.x) & 3)) + 499200))];
    placeholder_shared[((((int)threadIdx.x) + 3950))] = placeholder1[((((((((int)threadIdx.x) + 3950) >> 2) * 512) + (k_outer_outer * 4)) + ((((int)threadIdx.x) + 2) & 3)))];
    __syncthreads();
    T_dense[(0)] = (T_dense[(0)] + (placeholder_d_shared[(0)] * placeholder_shared[((((int)threadIdx.x) * 16))]));
    T_dense[(4)] = (T_dense[(4)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 800))]));
    T_dense[(8)] = (T_dense[(8)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1600))]));
    T_dense[(12)] = (T_dense[(12)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2400))]));
    T_dense[(16)] = (T_dense[(16)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3200))]));
    T_dense[(1)] = (T_dense[(1)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 4))]));
    T_dense[(5)] = (T_dense[(5)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 804))]));
    T_dense[(9)] = (T_dense[(9)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1604))]));
    T_dense[(13)] = (T_dense[(13)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2404))]));
    T_dense[(17)] = (T_dense[(17)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3204))]));
    T_dense[(2)] = (T_dense[(2)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 8))]));
    T_dense[(6)] = (T_dense[(6)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 808))]));
    T_dense[(10)] = (T_dense[(10)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1608))]));
    T_dense[(14)] = (T_dense[(14)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2408))]));
    T_dense[(18)] = (T_dense[(18)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3208))]));
    T_dense[(3)] = (T_dense[(3)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 12))]));
    T_dense[(7)] = (T_dense[(7)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 812))]));
    T_dense[(11)] = (T_dense[(11)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1612))]));
    T_dense[(15)] = (T_dense[(15)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2412))]));
    T_dense[(19)] = (T_dense[(19)] + (placeholder_d_shared[(0)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3212))]));
    T_dense[(0)] = (T_dense[(0)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1))]));
    T_dense[(4)] = (T_dense[(4)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 801))]));
    T_dense[(8)] = (T_dense[(8)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1601))]));
    T_dense[(12)] = (T_dense[(12)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2401))]));
    T_dense[(16)] = (T_dense[(16)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3201))]));
    T_dense[(1)] = (T_dense[(1)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 5))]));
    T_dense[(5)] = (T_dense[(5)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 805))]));
    T_dense[(9)] = (T_dense[(9)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1605))]));
    T_dense[(13)] = (T_dense[(13)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2405))]));
    T_dense[(17)] = (T_dense[(17)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3205))]));
    T_dense[(2)] = (T_dense[(2)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 9))]));
    T_dense[(6)] = (T_dense[(6)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 809))]));
    T_dense[(10)] = (T_dense[(10)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1609))]));
    T_dense[(14)] = (T_dense[(14)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2409))]));
    T_dense[(18)] = (T_dense[(18)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3209))]));
    T_dense[(3)] = (T_dense[(3)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 13))]));
    T_dense[(7)] = (T_dense[(7)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 813))]));
    T_dense[(11)] = (T_dense[(11)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1613))]));
    T_dense[(15)] = (T_dense[(15)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2413))]));
    T_dense[(19)] = (T_dense[(19)] + (placeholder_d_shared[(1)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3213))]));
    T_dense[(0)] = (T_dense[(0)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2))]));
    T_dense[(4)] = (T_dense[(4)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 802))]));
    T_dense[(8)] = (T_dense[(8)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1602))]));
    T_dense[(12)] = (T_dense[(12)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2402))]));
    T_dense[(16)] = (T_dense[(16)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3202))]));
    T_dense[(1)] = (T_dense[(1)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 6))]));
    T_dense[(5)] = (T_dense[(5)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 806))]));
    T_dense[(9)] = (T_dense[(9)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1606))]));
    T_dense[(13)] = (T_dense[(13)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2406))]));
    T_dense[(17)] = (T_dense[(17)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3206))]));
    T_dense[(2)] = (T_dense[(2)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 10))]));
    T_dense[(6)] = (T_dense[(6)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 810))]));
    T_dense[(10)] = (T_dense[(10)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1610))]));
    T_dense[(14)] = (T_dense[(14)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2410))]));
    T_dense[(18)] = (T_dense[(18)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3210))]));
    T_dense[(3)] = (T_dense[(3)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 14))]));
    T_dense[(7)] = (T_dense[(7)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 814))]));
    T_dense[(11)] = (T_dense[(11)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1614))]));
    T_dense[(15)] = (T_dense[(15)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2414))]));
    T_dense[(19)] = (T_dense[(19)] + (placeholder_d_shared[(2)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3214))]));
    T_dense[(0)] = (T_dense[(0)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3))]));
    T_dense[(4)] = (T_dense[(4)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 803))]));
    T_dense[(8)] = (T_dense[(8)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1603))]));
    T_dense[(12)] = (T_dense[(12)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2403))]));
    T_dense[(16)] = (T_dense[(16)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3203))]));
    T_dense[(1)] = (T_dense[(1)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 7))]));
    T_dense[(5)] = (T_dense[(5)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 807))]));
    T_dense[(9)] = (T_dense[(9)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1607))]));
    T_dense[(13)] = (T_dense[(13)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2407))]));
    T_dense[(17)] = (T_dense[(17)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3207))]));
    T_dense[(2)] = (T_dense[(2)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 11))]));
    T_dense[(6)] = (T_dense[(6)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 811))]));
    T_dense[(10)] = (T_dense[(10)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1611))]));
    T_dense[(14)] = (T_dense[(14)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2411))]));
    T_dense[(18)] = (T_dense[(18)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3211))]));
    T_dense[(3)] = (T_dense[(3)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 15))]));
    T_dense[(7)] = (T_dense[(7)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 815))]));
    T_dense[(11)] = (T_dense[(11)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 1615))]));
    T_dense[(15)] = (T_dense[(15)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 2415))]));
    T_dense[(19)] = (T_dense[(19)] + (placeholder_d_shared[(3)] * placeholder_shared[(((((int)threadIdx.x) * 16) + 3215))]));
  }
  for (int ax1_inner = 0; ax1_inner < 4; ++ax1_inner) {
    T_add[(((((int)threadIdx.x) * 4) + ax1_inner))] = (T_dense[(ax1_inner)] + placeholder2[(((((int)threadIdx.x) * 4) + ax1_inner))]);
    T_add[((((((int)threadIdx.x) * 4) + ax1_inner) + 200))] = (T_dense[((ax1_inner + 4))] + placeholder2[((((((int)threadIdx.x) * 4) + ax1_inner) + 200))]);
    T_add[((((((int)threadIdx.x) * 4) + ax1_inner) + 400))] = (T_dense[((ax1_inner + 8))] + placeholder2[((((((int)threadIdx.x) * 4) + ax1_inner) + 400))]);
    T_add[((((((int)threadIdx.x) * 4) + ax1_inner) + 600))] = (T_dense[((ax1_inner + 12))] + placeholder2[((((((int)threadIdx.x) * 4) + ax1_inner) + 600))]);
    T_add[((((((int)threadIdx.x) * 4) + ax1_inner) + 800))] = (T_dense[((ax1_inner + 16))] + placeholder2[((((((int)threadIdx.x) * 4) + ax1_inner) + 800))]);
  }
}


